#! /bin/env python3

"""
Quality check using FastQC
==========================

Author: Andrés García García @ May 2018

About the project
-----------------
NOTE: This is the first script in the pipeline of the project.

We are trying to detect if there are changes in the expression of
long non-coding RNAs between the left and right hemisphere of a mouse's
brain (telencephalon). For this, 3 samples where taken and sequenced using
RNAseq. For more information about RNAseq, see: 
https://galaxyproject.org/tutorials/rb_rnaseq/


The data
--------
The input data for the current script are the raw FASTQ files from the
RNAseq experiment.

    
The analysis
------------
We are basing our protocol on the instructions provided in:
https://davetang.org/muse/2017/10/25/getting-started-hisat-stringtie-ballgown/
https://www.biostars.org/p/207680/#207685

Procedure
---------
All the FASTQ files are already in a single folder (data/), so, we invoke
fastq on each of them.

Why do we need to generate another script? In order to get computing resources, we need to
enqueue the job through the SGE tasks system, this is done by specifying the task in a script.
That is the script that is generated here and submitted to the queue system through 'qsub' at 
the end of this file.

"""

import subprocess
from pathlib import Path


def run(command, **kwargs):
    """Execute a command through the shell. Doesn't capture output."""
    command = command.split()
    subprocess.run(command, **kwargs)
# ---

def get_output(command):
    """Execute a command through the shell, get the output as a string.
    """
    command = command.split()
    bytes_output = subprocess.check_output(command)
    return bytes_output.decode('UTF-8')
# ---


#### <<<<<< MAIN PROCEDURE >>>>>>> ####

data_path = Path('./data').resolve()
output_path = Path('./quality').resolve()

## 1. --- Generate the commands.
#          ... & search the files.
input_files = (str(file) 
                   for file in data_path.glob('*.fastq'))


command_template = f"fastqc -o {output_path} {{inputf}}"
commands = [command_template.format(inputf=file) 
                for file in input_files]

commands_str = "\n".join( f"commands[{i+1}]='{s}'" 
                              for i,s in enumerate(commands) )



# 1. --- Assemble the script.
#        Create the script that will launch the paralell jobs.

RAM = '8'
python3_exec_path = get_output('which python3')

script = f"""\
#! {python3_exec_path}

#Run through this shell
#$ -S {python3_exec_path}

# Use current working directory
#$ -cwd

# Join stdout and stderr
#$ -j y

# If modules are needed, source modules environment (Do not delete the next line):
#. /etc/profile.d/modules.sh

# Name the job
#$ -N quality_check

# Pass environment
#$ -V

# Work with {RAM}G RAM
#$ -l vf={RAM}G

# Use as many jobs as needed
#$ -t 1-{len(commands)}


'''
Quality check using FastQC
--------------------------

The current script was autogenerated with the 
file `script.quality_check.py`, look there for documentation.

'''

import os
import subprocess
from pathlib import Path


# The commands to be executed
commands = dict()
{commands_str}

# Fetch the job id
job_id = int( os.environ['SGE_TASK_ID'] )

# Fetch the command corresponding to the current job
command = commands[job_id]


# Execute the command
print("Executing command:", command)

subprocess.run(command.split()) # <-- Here it is executed, splitting is 
                                #     necessary to pass the arguments 
                                #     appropriately
                       
print("Finished execution.")
"""

script_name = 'script.autogenerated.quality_check_jobs.py'

with open(script_name, 'w') as outf:
    outf.write(script)



# 2. -- Launch the job
run(f"qsub {script_name}")
